title: "(RFC Title)"
labels: ["research", "draft"]
body:
  - type: markdown
    attributes:
      value: |
        > [**Guideline**](https://github.com/cbgradschool/.github/wiki/RFC-Guideline)
  - type: markdown
    attributes:
      value: |
        ## Research

  - type: input
    id: reviewed-by
    attributes:
      label: "To be reviewed by:"
      description: "A comma separated list of github username handles."
      placeholder: "@samueljoli"
    validations:
      required: true
  - type: input
    id: related-to
    attributes:
      label: "Related to issue(s):"
      description: "A comma separated list of github issues."
      placeholder: "#1"
    validations:
      required: true
  - type: checkboxes
    id: changes
    attributes:
      label: What type of change is this introducing?
      description: You may select more than one.
      options:
        - label: New feature
        - label: New subsystem
        - label: Change to an existing API
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "What is this proposal solving or introducing? Why does the problem or opportunity matter? How does the problem or opportunity affect the user?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "Describe your solution and how it’s going to solve the problem or introduce the opportunity. This is likely the largest section of your proposal and might even include some high-level diagrams if you are proposing code changes. While all important aspects need to be covered, also keep in mind that shorter documents are more likely to be read."
    validations:
      required: true
